# Generated by Django 5.0.6 on 2024-06-09 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elonlar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ads',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elonlar.category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ads_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elonlar.ads'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ads',
            name='mahalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elonlar.mahalla'),
        ),
        migrations.AddField(
            model_name='streert',
            name='mahalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='street', to='elonlar.mahalla'),
        ),
        migrations.AddField(
            model_name='ads',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elonlar.streert'),
        ),
        migrations.AlterUniqueTogether(
            name='streert',
            unique_together={('name', 'mahalla')},
        ),
    ]
