# Generated by Django 5.0.6 on 2024-06-09 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('tel_nimber', models.CharField(max_length=13)),
                ('profile_photo', models.ImageField(default='profile_images/profile_default_image.png/', upload_to='photo/profile_photos')),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
    ]
